import type { Metadata } from "next";
import { Ubuntu} from "next/font/google";
import "./globals.css";
import NavbarComponent from "../components/header/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import localFont from "next/font/local";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const ubuntu = Ubuntu({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
})
export const myFont = localFont({
  src: '../../public/fonts/Howdybun.otf',
  variable: "--font-howdybun",
  display: "swap",
})
export const khmerFont = localFont({
  src: '../../public/fonts/Moul-Regular.ttf',
  variable: "--font-khmer",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${ubuntu.variable} ${khmerFont.variable} antialiased`}>
        <ErrorBoundary errorComponent={Error}>
          <NavbarComponent />
          <Suspense fallback={<Loading />}>
            {modal}
            {children}
          </Suspense>
        </ErrorBoundary>
        {/* <script src="https://unpkg.com/flowbite@1.4.1/dist/flowbite.js"></script> */}
      </body>
    </html>
  );
}
